[package]
name = "story"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
gpui.workspace = true
ui.workspace = true
ui_macros.workspace = true
